import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer';
import Header from '../components/Header'
import LargeCard from '../components/LargeCard';
import MediumCard from '../components/MediumCard';
import SmallCard from '../components/SmallCard';


export default function Home({ exploreData, cardsData }) {
  console.log(exploreData);
  return (
    <div className=''>
      <Head>
        <title>Air-bnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />
      <main className='max-w-7xl m-auto px-8 sm:px-16'>

        <section className='pt-6'>
          <h1 className='text-4xl font-semibold pb-5'>Explore nearby</h1>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {
              exploreData?.map(({ img, location, distance }) => {
                return <SmallCard
                  key={img}
                  img={img}
                  location={location}
                  distance={distance}
                />
              })
            }
          </div>
        </section>

        <section>
          <h1 className='text-4xl font-semibold py-8'>Live enywhere</h1>
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-4 -ml-3'>
            {
              cardsData?.map(({ img, title }) => {
                return <MediumCard
                  key={img}
                  img={img}
                  title={title}
                />
              })
            }
          </div>
        </section>

        <section>
          <LargeCard
            img='https://links.papareact.com/4cj'
            title='The Greatest Outdoors'
            description='Wishlists curated by airbnb.'
            buttonText='Get inspired'
          />
        </section>
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://links.papareact.com/pyp').
    then(
      (res) => res.json()
    )
  const cardsData = await fetch('https://links.papareact.com/zp1').
    then(
      (res) => res.json()
    )
  return {
    props: {
      exploreData,
      cardsData
    }
  }
}